### ISSUE TITLE
Trouble connecting to loom files

### ISSUE THREAD

**Issue by lincoln-harris** [mojaveazure/loomR#11]
I'm unable to connect to loom files. Using the command 
`lfile <- connect(filename = "l1_amygdala.loom", mode = "r+")`
I receive the following error message: 
`Error in obj$ls(..., recursive = recursive) : 
  unused argument (full.names = TRUE)`
Any idea whats going on? 
Thanks
Lincoln

**Comment by mojaveazure** [comment]
Try updating your version of [loomR](https://github.com/mojaveazure/loomR) and [hdf5r](https://github.com/hhoeflin/hdf5r). The GitHub version of hdf5r contains numerous stability improvements that the development (latest) version of loomR depends upon.

```R
devtools::install_github(repo = 'hhoeflin/hdf5r') # Update hdf5r for stability improvements
devtools::install_github(repo = 'mojaveazure/loomR', ref = 'develop') # Update loomR for up-to-date functions
```

**Comment by lincoln-harris** [comment]
That did the trick. Thanks
