### ISSUE TITLE
Creating and connecting to loom file created in R

### ISSUE THREAD

**Issue by majorkazer** [mojaveazure/loomR#12]
Hello,

I have tried creating a loom file using create with the default parameters. However, when I try to connect to that file afterward, I get the following error: 

```R
Error in obj$ls(..., recursive = recursive) : 
  unused argument (full.names = TRUE)
```

This file also cannot be read by the current version of loompy.

R version 3.4.4
Platform: x86_64-apple-darwin15.6.0 (64-bit)
OS: El Capitan

**Comment by mojaveazure** [comment]
Please see #11 for the connection error.

What error are you getting when attempting to connect with loompy?

**Comment by majorkazer** [comment]
Looks like I am not able to properly install hdf5r from their git; I didn't notice at first. Someone else has created an [issue](https://github.com/hhoeflin/hdf5r/issues/97) for the same compilation error I had, so I will wait for a fix.

**Comment by mojaveazure** [comment]
If you're looking to install hdf5r while Holger works on getting hdf5r compatible with HDF5 1.10.2, you can use [Homebrew](https://brew.sh) to install an older version (I'd recommend you use Homebrew to install most programs for macOS as it takes care of dependencies, upgrades, and easily switching to old versions of software). I've tested this with HDF5 1.10.1_2 under R 3.4.4 and 3.5.0 under macOS 10.13.3 High Sierra, and was able to install hdf5r successfully.

If you've installed HDF5 through Homebrew, you can see which versions you have installed as such:
```bash
$ brew info hdf5
hdf5: stable 1.10.2 (bottled) # Latest version installed
File format designed to store large amounts of data
https://www.hdfgroup.org/HDF5
/usr/local/Cellar/hdf5/1.10.1_2 (265 files, 14.6MB)
  Poured from bottle on 2017-11-06 at 21:18:59
/usr/local/Cellar/hdf5/1.10.2 (261 files, 15MB) * # The asterisk shows which version is active
  Poured from bottle on 2018-05-01 at 14:42:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hdf5.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✔
Required: gcc ✘, szip ✔
==> Options
--with-mpi
	Enable parallel support
```

Here, it shows that I have HDF5 1.10.1_2 and 1.10.2 installed, and using 1.10.2; to switch to the older, working version, I use `brew switch`:
```bash
$ brew switch hdf5 1.10.1_2
Cleaning /usr/local/Cellar/hdf5/1.10.2
Cleaning /usr/local/Cellar/hdf5/1.10.1_2
159 links created for /usr/local/Cellar/hdf5/1.10.1_2
$ brew info hdf5
hdf5: stable 1.10.2 (bottled) # Still shows latest version installed
File format designed to store large amounts of data
https://www.hdfgroup.org/HDF5
/usr/local/Cellar/hdf5/1.10.1_2 (265 files, 14.6MB) * # Asterisk now shows 1.10.1_2 is active
  Poured from bottle on 2017-11-06 at 21:18:59
/usr/local/Cellar/hdf5/1.10.2 (261 files, 15MB)
  Poured from bottle on 2018-05-01 at 14:42:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hdf5.rb
==> Dependencies
Build: autoconf ✔, automake ✘, libtool ✔
Required: gcc ✘, szip ✔
==> Options
--with-mpi
	Enable parallel support
```

If you don't have an older version of HDF5 installed, you can install it through Homebrew as follows:
```
brew install hdf5@1.10.1_2
```

**Comment by majorkazer** [comment]
Homebrew was unable to install a previous version of hdf5.

I downloaded the source of 1.10.1, compiled, and then installed hdf5r via `R CMD INSTALL` and now no longer have issues in R or python.

Thanks!

**Comment by gewirtz** [comment]
@majorkazer Would you mind pointing me to where you found the source code for 1.10.1 ? I am having the same issue you did. Thanks so much!!

**Comment by majorkazer** [comment]
They found the source code for previous versions here:
https://portal.hdfgroup.org/display/support/Download+HDF5
