### ISSUE TITLE
the warning after connect to the loom file:Moving edge groups to graph groups to conform to loom v2.0.1

### ISSUE THREAD

**Issue by Sophia409** [mojaveazure/loomR#31]
```
> lfile <- connect(filename = "/home/yuhong/snap/firefox/common/Download/l1_thalamus.loom", mode = "r+")
Moving edge groups to graph groups to conform to loom v2.0.1 
```
Hello,can you tell me what did this sentence (Moving edge groups to graph groups to conform to loom v2.0.1 )means?What I need to do?Is it normal?
@ChristophH @andrewwbutler @satijalab @mojaveazure

**Comment by mojaveazure** [comment]
This is simply renaming some the loom file's groups to match the standards issued in [loom v2.0.1](http://linnarssonlab.org/loompy/index.html) (we don't issue the standard, we simply provide a standards-compliant interface for R).
