### ISSUE TITLE
Support for R 3.5+?

### ISSUE THREAD

**Issue by zaczap** [mojaveazure/loomR#39]
Not sure if there's a reason for the 3.4.x requirement?

**Comment by mojaveazure** [comment]
Hi @zaczap,

Could you tell me where you see a requirement for R 3.4 or lower? I use R 3.5.3 on my machine and am able to use loomR just fine.

**Comment by zaczap** [comment]
Hi @mojaveazure -- apologies since I'm not sure how I've since fixed it, but I've definitely overcome the problem since I originally marked opened this issue (I updated a host of packages in and around the formal release of Seurat V3). It's working great--thanks for making this available!
