### ISSUE TITLE
Error combining loom outputs from velocyto

### ISSUE THREAD

**Issue by davisidarta** [mojaveazure/loomR#46]
Hello loomR team!

I'm using loomR in order to work with loom files in R. I'm currently working with the outputs of velocyto from two different BAM files and would like to merge them. However, using the `combine `function renders me the following error:
```

> s <- loomR::connect('aCSF_O6S97.loom', mode ='r+')
> l <- loomR::connect(file = 'Leptin_SLQP8.loom', mode ='r+')
> 
> bl <- combine(list('aCSF_O6S97.loom', 'Leptin_SLQP8.loom'), chunk.size = 100, filename = 'combined.loom')
Validating 2 input loom files
  |======================================================================================================================| 100%
Error in dataset_create_pl$set_chunk(chunk_dims) : HDF5-API Errors:
    error #000: ../../../src/H5Pdcpl.c in H5Pset_chunk(): line 2030: all chunk dimensions must be positive
        class: HDF5
        major: Invalid arguments to routine
        minor: Out of range
In addition: Warning messages:
1: In max(nchar(x)) : no non-missing arguments to max; returning -Inf
2: In self$set_size(size) : NAs introduced by coercion to integer range

```

I was able to work with each of the loom files individualy in Seurat and Pagoda2. Any insights on what might be going on? I've installed loomR through the develop branch and I'm using R 3.6.

**Comment by fentouxungui** [comment]
I got the same error when combining two loom files generated from the velocity pipeline when using loomR package, any help?

**Comment by kaizen89** [comment]
@davisidarta @fentouxungui did you find any solution?

**Comment by davisidarta** [comment]
Dear @kaizen89 

My workaround this issue was to process the FASTQ files with the kb-python pipeline, which implements RNA velocity computation and doesn't require loom formats to work properly. Here's a link to the [documentation](https://www.kallistobus.tools/ ). I stopped using loom files altogether.

KB is really well documented. After creating Seurat objects for each of the data sets, it's really easy to merge them with either `merge()` (if you don't have significant batch effects) or with Seurat CCA anchor-based integration. 

Note that you'll need to process spliced and unspliced data in separate assays (either with `NormalizeData`, `FindVariableFeatures`, `ScaleData` or with `SCTransform`) in order to compute RNA velocity properly using Seurat. After that, just follow this RNA velocity with Seurat [vignette](https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/velocity.html).

All the best and good luck!
