### ISSUE TITLE
Where to store pca/tsne results in loomR?

### ISSUE THREAD

**Issue by yueqiw** [mojaveazure/loomR#6]
Hi,

I use loomR to convert Seurat objects into `.loom` files to read into other packages. Everything works wells except that the `@dr` from Seurat objects containing dimension reduction results (pca/tsne) are not saved into `.loom` files. Hope there is a way to implement this. Thanks!

Yueqi

**Comment by mojaveazure** [comment]
If Seurat's convert function doesn't automatically bring `dr` objects over, you can do it with the development version of loomR by storing two-dimensional matrices in `row_attrs` and `col_attrs`. You can use the `add.col.attribute` to add the cell embeddings and `add.row.attribute` to add the gene loadings.

Install the development version of loomR with
```R
devtools::install_github(repo = 'mojaveazure/loomR', ref = 'develop')
```

**Comment by yueqiw** [comment]
Thanks!
