### ISSUE TITLE
get.attribute.df(): unused argument (attribute.names = )

### ISSUE THREAD

**Issue by jasminelmah** [mojaveazure/loomR#76]
Hi!

I just installed loomR_0.2.1.9000  from Github. I've encountered this error while trying to follow the tutorial:

> row.attrs <- names(lfile$row.attrs)
> attr.df <- lfile$get.attribute.df(MARGIN=1, attribute.names=row.attrs)
> Error in lfile$get.attribute.df(MARGIN = 1, attribute.names = row.attrs) : 
>  unused argument (attribute.names = row.attrs)

I don't see where I've gone wrong - I am following the tutorial. Can you catch something?

I am able to access the matrix itself, but I need access to the gene names (row names) and cell ID names (column names) too, in addition to other annotated data.

Thanks for your help!

**Comment by niehu2018** [comment]
try the following code:
```
library(dplyr)
attr.df <- lfile$get.attribute.df(MARGIN = 2, col.names = "cell_names", row.names = "gene_names")
attr.df %>% class # data.frame
attr.df %>% colnames # cell_names, nGene, nUMI, orig.ident
attr.df %>% nrow # 2700
```
generate the whole data.frame, then select what you want

**Comment by jasminelmah** [comment]
Thanks!
