### ISSUE TITLE
Convert function missing

### ISSUE THREAD

**Issue by batson** [mojaveazure/loomR#9]
The function Convert (present in the tutorial: http://satijalab.org/loomR/loomR_tutorial.html) appears not to be in the package. Is it on the roadmap? Am I looking in the wrong repo?

**Comment by mojaveazure** [comment]
Hi Joshua,

The Convert function is part of [Seurat](https://github.com/satijalab/Seurat/tree/loom), not part of loomR.

loom support in Seurat is still a work in progress, but you can check it out by looking at the loom branch of Seurat. If you'd like to install it, you can use
```R
devtools::install_github(repo = 'satijalab/Seurat', ref = 'loom')
```

**Comment by batson** [comment]
Aha! Thanks for the clarification. The base problem we're trying to solve is how to get our Seurat object over to python, and passing through loom seemed like the most direct way.
